#konfigurasi mongodb
spring:
    data:
        mongodb:
            database: th-dev-2016
            host: 127.0.0.1
            port: 27017

#konfigurasi jackson
    jackson:
        serialization:
            indent-output: true
            
    # spring datasource jpa
    datasource: 
        driver-class-name: org.h2.Driver
        url: jdbc:h2:file:./database/customoauth2
        username: root
        password: root
        poolName: SpringBootHikariCP
        maximumPoolSize: 5
        minimumIdle: 3
        maxLifetime: 2000000
        connectionTimeout: 30000
        idleTimeout: 30000